### ISSUE TITLE
Highfive is welcoming existing contributors as new

### ISSUE THREAD

**Issue by jdm** [nick29581/highfive#38]
A workaround would be to use per_page=10000 instead.

**Comment by jdm** [comment]
I lied, there's still a Link header containing
```
<https://api.github.com/repositories/724712/contributors?page=2>; rel="next", <https://api.github.com/repositories/724712/contributors?page=27>; rel="last"
```
so I'm not sure why highfive is greeting long-time contributors.

**Comment by nick29581** [comment]
This seems to be limited to a few users - @Aatch and 'Yurumu' (that isn't in fact a GitHub user, so not sure exactly who is having the problem). In @Aatch's case, the problem seems to be that he is not on the list of contributors for Rust. That seems to be a GitHub bug, not ours.

We could probably maintain a list of people who are known contributors to a repo and check that list as well as the contributors list from GitHub. In fact, that would save us an API call in many cases, so we could add contributors who are on the GitHub list too. Although this is a bit of a hack, it is better than annoying regular contributors.

**Comment by jdm** [comment]
Yurume == @lifthrasiir

**Comment by Aatch** [comment]
@nick29581 how about using a local database of contributors that gets populated as highfive sees new contributors? If they're not in that list, add them and then make the call to see if they're in the contributor list. Basically just maintain your own database of contributors and use Github to fill in the gaps.

**Comment by nick29581** [comment]
I hope I have fixed this, at least for @Aatch and @lifthrisir, by adding a contributors section to the json file for a repo. We could extend this by adding all contributors and only checking the API when that fails, or we could maintain our own DB to do pretty much the same thing.

**Comment by nick29581** [comment]
Closing in favour of #41, please re-open if my fix did not in fact fix things
